name: example - static
on:
  push:
  #  branches:
  #    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: static
        run: |
          echo 'static example'
          cd example/static
      - uses: amondnet/now-deployment@v1
        id: now-deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--prod'
